#!/usr/bin/env bash

# this script is meant to be ran from the ArkScript folder, to be able to access the ArkScript binary easily
ARKSCRIPT=$(pwd)/build/arkscript
ARKLIB=$(pwd)/lib

Reset='\033[0m'
Red='\033[0;31m'
Purple='\033[0;35m'

total_time=0

errors=0

for t in lib/modules/"${1:-src}"/*/tests/; do
    start=$(date +%s%N | tr -d 'N')

    echo -n "Running ${t}..."
    (cd "$t" || exit 1; source ./run "$ARKSCRIPT" "$ARKLIB")
    code=$?
    if [[ $code != 0 ]]; then
      errors=$((errors + 1))
    fi

    end=$(date +%s%N | tr -d 'N')
    elapsed=$((end - start))
    total_time=$((total_time + elapsed))
    seconds=$((elapsed / 1000000000))
    decimals=$((elapsed - (seconds * 1000000000) ))
    runtime="${seconds}.${decimals}sec"

    echo -en "-- in ${Purple}${runtime}${Reset}"
    if [[ $code != 0 ]]; then
      echo -e " - ${Red}FAILED${Reset}"
    else
      echo ""
    fi
done

seconds=$((total_time / 1000000000))
decimals=$((total_time - (seconds * 1000000000) ))
runtime="${seconds}.${decimals}sec"
echo -e "Completed in ${Purple}${runtime}${Reset}"

echo -e "Failures: ${Red}${errors}${Reset}"
