#!/usr/bin/env bash

# this script is meant to be ran from the ArkScript folder, to be able to access the ArkScript binary easily
ARKSCRIPT=$(pwd)/build/arkscript
ARKLIB=$(pwd)/lib

Reset='\033[0m'
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'

total_time=0

for t in lib/modules/${1:-src}/*/tests/; do
    start=$(date +%s%N | tr -d 'N')

    echo -n "Running ${t}..."
    (cd $t; source ./run $ARKSCRIPT $ARKLIB)
    code=$?

    end=$(date +%s%N | tr -d 'N')
    elapsed=$((end - start))
    total_time=$((total_time + elapsed))
    seconds=$((elapsed / 1000000000))
    decimals=$((elapsed - (seconds * 1000000000) ))
    runtime="${seconds}.${decimals}sec"

    echo -e "-- in ${Purple}${runtime}${Reset}"
done

seconds=$((total_time / 1000000000))
decimals=$((total_time - (seconds * 1000000000) ))
runtime="${seconds}.${decimals}sec"
echo -e "Completed in ${Purple}${runtime}${Reset}"
