if (${ARK_REQUESTED_MODULES} MATCHES "(^\\*$|bitwise,)")
    add_subdirectory(bitwise)
endif ()
if (${ARK_REQUESTED_MODULES} MATCHES "(^\\*$|console,)")
    add_subdirectory(console)
endif ()
if (${ARK_REQUESTED_MODULES} MATCHES "(^\\*$|(ark_)?hash,)")
    add_subdirectory(ark_hash)
endif ()
if (${ARK_REQUESTED_MODULES} MATCHES "(^\\*$|http,)")
    add_subdirectory(http)
endif ()
