name: "CMake"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/*.*'
      - '*.md'
      - 'LICENCE'
      - '.gitignore'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Ubuntu Clang 16"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ArkScript-lang/Ark
          path: '.'
          submodules: recursive

      - shell: bash
        run: rm -r lib/modules

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: lib/modules

      - name: Update LLVM compilers
        shell: bash
        run: sudo apt-get install -y clang-16 lld-16 libc++-16-dev libc++abi-16-dev clang-tools-16

      - name: Configure CMake Ark
        shell: bash
        run: |
          cmake -Bbuild \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_C_COMPILER=clang-16 \
            -DCMAKE_CXX_COMPILER=clang++-16 \
            -DARK_BUILD_EXE=On -DARK_UNITY_BUILD=On \
            -DARK_BUILD_MODULES=On -DARK_MOD_ALL=On -DARK_MOD_DRAFT=On

      - name: Build ArkScript
        shell: bash
        run: cmake --build build --config $BUILD_TYPE -j $(nproc)

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run src module tests
        shell: bash
        run: ./lib/modules/.github/run-tests src

      - name: Run draft module tests
        shell: bash
        run: ./lib/modules/.github/run-tests draft
