name: "CMake"

on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/*.*'
      - '*.md'
      - 'LICENCE'
      - '.gitignore'
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Ubuntu Clang 11"

    steps:
    - uses: actions/checkout@v2
      if: contains(github.event.head_commit.message, '[skip ci]') == false
      with:
        repository: ArkScript-lang/Ark
        path: '.'
        submodules: recursive

    - shell: bash
      run: rm -r lib/modules

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        path: lib/modules

    - name: Update LLVM compilers
      shell: bash
      run: sudo apt-get install -y clang-11 lld-11 libc++-11-dev libc++abi-11-dev clang-tools-11

    - name: Configure CMake Ark
      shell: bash
      run: |
        cmake -Bbuild \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_C_COMPILER=clang-11 \
          -DCMAKE_CXX_COMPILER=clang++-11 \
          -DARK_BUILD_EXE=On -DARK_BUILD_MODULES=On -DARK_MOD_ALL=On

    - name: Build ArkScript
      shell: bash
      run: cmake --build build --config $BUILD_TYPE

    - shell: bash
      run: |
        mkdir -p artifact
        cp build/arkscript artifact/
        cp lib/*.arkm artifact/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: temp
        path: artifact

    - name: Run module tests
      shell: bash
      run: |
        ARKSCRIPT=$(pwd)/build/arkscript
        ARKLIB=$(pwd)/lib
        for t in lib/modules/*/tests/; do
          echo "Running ${t}..."
          (cd $t; $ARKSCRIPT main.ark --lib $ARKLIB)
        done
